# Generated by Django 4.0.1 on 2022-01-24 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Register',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=10)),
                ('last_name', models.CharField(max_length=10)),
                ('email', models.EmailField(max_length=10)),
                ('phone', models.BigIntegerField(max_length=10)),
                ('street_address', models.CharField(max_length=100)),
                ('billing_address', models.CharField(max_length=100)),
                ('town', models.CharField(max_length=12)),
                ('state', models.CharField(max_length=15)),
                ('postcode', models.CharField(max_length=6)),
                ('password', models.CharField(max_length=12)),
            ],
        ),
    ]
