# Generated by Django 4.0.1 on 2022-01-25 06:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_register_email_alter_register_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='register',
            name='password',
        ),
    ]
