# Generated by Django 4.0.1 on 2022-01-26 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_remove_register_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='register',
            name='billing_address',
        ),
        migrations.RemoveField(
            model_name='register',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='register',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='register',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='register',
            name='postcode',
        ),
        migrations.RemoveField(
            model_name='register',
            name='state',
        ),
        migrations.RemoveField(
            model_name='register',
            name='street_address',
        ),
        migrations.RemoveField(
            model_name='register',
            name='town',
        ),
        migrations.AddField(
            model_name='register',
            name='username',
            field=models.CharField(default=1, max_length=18),
            preserve_default=False,
        ),
    ]
