# Generated by Django 4.0.1 on 2022-01-28 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_billing_details'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billing_details',
            name='phone',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='billing_details',
            name='postcode',
            field=models.BigIntegerField(),
        ),
    ]
