# Generated by Django 4.0 on 2022-01-04 08:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myadmin', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Login',
            new_name='Contact',
        ),
    ]
