# Generated by Django 4.0 on 2022-01-04 09:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myadmin', '0002_rename_login_contact'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Contact',
            new_name='Login',
        ),
    ]
