# Generated by Django 4.0.1 on 2022-01-26 15:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myadmin', '0004_add_category'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Add_category',
            new_name='AddCategory',
        ),
    ]
