# Generated by Django 4.0.1 on 2022-01-28 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myadmin', '0005_rename_add_category_addcategory'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddSubCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=20)),
                ('subcategory', models.CharField(max_length=20)),
            ],
        ),
    ]
