# Generated by Django 4.0.1 on 2022-01-28 14:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myadmin', '0006_addsubcategory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='addsubcategory',
            name='category',
        ),
    ]
