# Generated by Django 4.0.1 on 2022-01-28 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myadmin', '0009_remove_addsubcategory_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='addsubcategory',
            name='category',
            field=models.CharField(default=None, max_length=20),
            preserve_default=False,
        ),
    ]
